lidar_ground_node:
  ros__parameters:
    treshold_ground_: 0.15 #this is for the oldest version of ground getter called LidarGround.cpp
    num_seg_: 50
    num_iter_: 30
    num_lpr_: 10
    th_seeds_: 1.0
    th_dist_: 0.3
    sensor_height_: 1.73

